import { StyleSheet, Dimensions, Platform, StatusBar } from "react-native";

const { width, height } = Dimensions.get("window");
const TEAL = '#00798C'; // App primary color
const WHITE = '#FFFFFF';
const LIGHT_GRAY = '#F5F5F5';
const DARK_GRAY = '#666';
const LIGHT_TEXT = '#999';

// Safe handling of StatusBar height for cross-platform compatibility
const statusBarHeight = Platform.OS === 'android' ? StatusBar.currentHeight || 0 : 0;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? statusBarHeight + 20 : statusBarHeight + 10,
    paddingBottom: 10,
    backgroundColor: WHITE,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  closeButton: {
    marginTop: 30,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f5f5f5",
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    marginTop: 30,
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  stepTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    marginVertical: 15,
  },
  scrollContent: {
    flex: 1,
    paddingHorizontal: 20,
  },
  stepContent: {
    paddingBottom: 20,
  },
  stepIndicatorsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 25,
    marginTop: 10,
  },
  stepIndicator: {
    width: 25,
    height: 6,
    backgroundColor: "#e0e0e0",
    marginHorizontal: 4,
    borderRadius: 3,
  },
  activeStepIndicator: {
    backgroundColor: TEAL,
  },
  label: {
    fontSize: 14,
    fontWeight: "500",
    color: "#666",
    marginBottom: 8,
    marginTop: 12,
  },
  input: {
    width: "100%",
    height: 48,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 15,
    backgroundColor: WHITE,
  },
  dropdown: {
    width: "100%",
    height: 48,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: WHITE,
  },
  dropdownIcon: {
    marginRight: 8,
  },
  dropdownText: {
    fontSize: 15,
    color: "#333",
  },
  rowContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  columnContainer: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  
  // Modal content container
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    width: '100%',
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  
  // Modal title
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 16,
    textAlign: 'center',
  },
  
  // Place type item in dropdown
  placeTypeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  
  // Place type name text
  placeTypeName: {
    fontSize: 16,
    color: '#333',
    flex: 1,
  },
  countryDropdownIcon: {
    position: "absolute",
    right: 12,
    top: 15,
  },
  countryDropdown: {
    position: "absolute",
    top: 48,
    left: 0,
    right: 0,
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    zIndex: 1000,
    elevation: 3,
  },
  countryItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  countryFlag: {
    fontSize: 16,
    marginRight: 8,
  },
  countryName: {
    fontSize: 14,
    color: "#333",
  },
  locationButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: TEAL,
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 15,
  },
  locationButtonText: {
    color: WHITE,
    fontWeight: "500",
    marginLeft: 6,
  },
  openingHoursRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  dayDropdown: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingHorizontal: 10,
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: WHITE,
  },
  timesSeparator: {
    marginHorizontal: 8,
    color: "#999",
  },
  timeInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingHorizontal: 10,
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: WHITE,
  },
  hoursButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: TEAL,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  photoUploadArea: {
    marginTop: 15,
  },
  addPhotoButton: {
    width: "100%",
    height: 150,
    borderWidth: 2,
    borderColor: "#ddd",
    borderStyle: "dashed",
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
  },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  photoContainer: {
    width: width * 0.4,
    height: width * 0.3,
    marginBottom: 15,
    borderRadius: 10,
    overflow: "hidden",
    position: "relative",
  },
  photo: {
    width: "100%",
    height: "100%",
  },
  removePhotoButton: {
    position: "absolute",
    top: 5,
    right: 5,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  navigationButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: WHITE,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  backButton: {
    flex: 0.3,
    height: 50,
    borderWidth: 1,
    borderColor: TEAL,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  backButtonText: {
    color: TEAL,
    fontWeight: "500",
  },
  nextButton: {
    flex: 0.65,
    height: 50,
    backgroundColor: TEAL,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  nextButtonText: {
    color: WHITE,
    fontWeight: "500",
  },
  
  // Thank You Screen Styles
  thankYouContainer: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 20,
  },
  profileImageContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#f5f5f5",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    marginVertical: 20,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  profileImage: {
    width: "100%",
    height: "100%",
    borderRadius: 40,
  },
  thankYouContent: {
    width: "100%",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  thankYouText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    marginBottom: 20,
  },
  contributingText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#333",
  },
  pointsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: 'rgba(113, 171, 157, 0.8)', // Using a non-blue color as requested
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    marginBottom: 20,
    width: "100%",
  },
  coinIcon: {
    width: 28,
    height: 28,
    marginRight: 8,
  },
  pointsText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  userProfileCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    backgroundColor: "#f8f9fa",
    borderRadius: 15,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#e9ecef",
  },
  userInfoContainer: {
    flex: 1,
  },
  usernameText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#343a40",
    marginBottom: 8,
  },
  userStatsContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 15,
  },
  statText: {
    marginLeft: 5,
    fontSize: 14,
    color: "#495057",
  },
  levelBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8f9fa",
    borderRadius: 20,
    padding: 8,
    borderWidth: 1,
    borderColor: TEAL,
  },
  badgeCoinIcon: {
    width: 16,
    height: 16,
    marginRight: 4,
  },
  levelText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#343a40",
  },
  achievementContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    borderRadius: 15,
    padding: 10,
    marginBottom: 10,
    width: "100%",
    borderWidth: 1,
    borderColor: "#e9ecef",
  },
  achievementText: {
    marginLeft: 10,
    fontSize: 16,
    fontWeight: "500",
    color: "#343a40",
  },
  placeContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    borderRadius: 15,
    padding: 10,
    marginBottom: 20,
    width: "100%",
    borderWidth: 1,
    borderColor: "#e9ecef",
  },
  placeText: {
    marginLeft: 10,
    fontSize: 16,
    fontWeight: "500",
    color: "#343a40",
  },
  doneButton: {
    width: "100%",
    height: 50,
    backgroundColor: TEAL,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  doneButtonText: {
    color: WHITE,
    fontSize: 16,
    fontWeight: "600",
  }
});

export default styles;